export const queryKeys = {
  community: (communityId: string | null | undefined) => ['community', communityId ?? 'none'] as const,
  charities: (communityId: string | null | undefined) => ['charities', communityId ?? 'none'] as const,
  posts: (communityId: string | null | undefined) => ['posts', communityId ?? 'none'] as const,
  businesses: (communityId: string | null | undefined, ownerId?: string | null) => ['businesses', communityId ?? 'none', ownerId ?? 'all'] as const,
  members: (communityId: string | null | undefined) => ['members', communityId ?? 'none'] as const,
  conversations: (userId: string | null | undefined) => ['conversations', userId ?? 'none'] as const,
  messages: (conversationId: string | null | undefined) => ['messages', conversationId ?? 'none'] as const,
  notifications: (userId: string | null | undefined) => ['notifications', userId ?? 'none'] as const,
  userSearch: (query: string) => ['user-search', query.trim().toLowerCase()] as const,
  communityBootstrap: (userId: string | null | undefined) => ['community-bootstrap', userId ?? 'none'] as const,
  communityBundle: (communityId: string | null | undefined) => ['community-bundle', communityId ?? 'none'] as const,
  conversationMessages: (conversationId: string | null | undefined) => ['conversation-messages', conversationId ?? 'none'] as const,
  invitePreview: (code: string | null | undefined) => ['invite-preview', code ?? 'none'] as const,
  communityById: (communityId: string | null | undefined) => ['community-by-id', communityId ?? 'none'] as const,
  featuredCharity: (communityId: string | null | undefined) => ['featured-charity', communityId ?? 'none'] as const,
  catHub: (communityId: string | null | undefined) => ['cat-hub', communityId ?? 'none'] as const,
  charityCampaignHistory: (communityId: string | null | undefined) => ['charity-campaign-history', communityId ?? 'none'] as const,
  charityTotals: (communityId: string | null | undefined) => ['charity-totals', communityId ?? 'none'] as const,
  currentUserProfile: () => ['current-user-profile'] as const,
  currentUserSessions: () => ['current-user-sessions'] as const,
  currentUserTwoFA: () => ['current-user-2fa'] as const,
  currentUserAuditLogs: () => ['current-user-audit-logs'] as const,
  liveInsights: (communityId: string | null | undefined) => ['live-insights', communityId ?? 'none'] as const,
  moderationLogs: (
    communityId: string | null | undefined,
    params?: { limit?: number; targetType?: string; targetId?: string },
  ) => ['moderation-logs', communityId ?? 'none', params?.limit ?? 'all', params?.targetType ?? 'all', params?.targetId ?? 'all'] as const,
  securityEvents: (
    communityId: string | null | undefined,
    params?: { resolved?: boolean; severity?: string; status?: string },
  ) => ['security-events', communityId ?? 'none', params?.resolved ?? 'all', params?.severity ?? 'all', params?.status ?? 'all'] as const,
  memberInsights: (communityId: string | null | undefined, userId: string | null | undefined) => ['member-insights', communityId ?? 'none', userId ?? 'none'] as const,
};
